### ISSUE TITLE
relativeName修改后scroll事件不生效了

### ISSUE THREAD

**Issue by 18dian** [pekonchan/scrollNav#12]
![image](https://user-images.githubusercontent.com/39373488/90016814-2ed7d000-dcdd-11ea-8c05-c63cc783430c.png)
![image](https://user-images.githubusercontent.com/39373488/90016868-4020dc80-dcdd-11ea-898c-275bbc49d651.png)

**Comment by 18dian** [comment]
原因是因为，父元素没有加height:100%，和overflow-y:auto，可以封装在组件内部

**Comment by pekonchan** [comment]
> 原因是因为，父元素没有加height:100%，和overflow-y:auto，可以封装在组件内部

你说的父元素是指？

**Comment by pekonchan** [comment]
因没相关更具体信息反馈。先关闭该issue
