### ISSUE TITLE
可否加个过渡动画？

### ISSUE THREAD

**Issue by inzaghihao** [pekonchan/scrollNav#13]
`
this.scrollContainer.scrollTo({
  top:this.offsetTops[`content${index}`] - this.scrollDeviation,
  behavior: "smooth"
}) 
`

**Comment by pekonchan** [comment]
> scrollTo

嗯嗯，这个建议很棒。这个过渡效果一直在TODO项中，今晚稍后点加上

**Comment by pekonchan** [comment]
> ` this.scrollContainer.scrollTo({ top:this.offsetTops[`content${index}`] - this.scrollDeviation, behavior: "smooth" }) `

嗯嗯，这个建议很棒。这个过渡效果一直在TODO项中，今晚稍后点加上

**Comment by pekonchan** [comment]
> `this.scrollContainer.scrollTo({ top:this.offsetTops[`content${index}`] - this.scrollDeviation, behavior: "smooth" })`

已经添加过渡效果，并添加相关选项和兼容性逻辑，已经发布最新npm包了。再次感谢您的建议
