### ISSUE TITLE
点击导航栏 ，导航栏就吸顶了

### ISSUE THREAD

**Issue by lvwenrui12** [pekonchan/scrollNav#16]
在导航栏没有在顶部的时候，点击导航栏 ，导航栏就吸顶了。

**Comment by pekonchan** [comment]
对不起一直没看到消息。估计之前不小心消了提醒。（时间有点长了，先关闭issue）

吸顶是因为你的内容要滚动到顶部，你的页面就要发生滚动，当滚动距离会遮盖导航栏，就会吸顶了。 是这么一个因果关系。就跟你手动滚动查看对应导航栏内容时的表现是一样的。

如果你想不吸顶，就需要调整一下你的页面布局，设置`relativeName`，指定你要相对于哪个容器滚动，而不是使用默认的相对整个html。
