### ISSUE TITLE
点击导航跳转了但是导航样式是错的

### ISSUE THREAD

**Issue by Tibbet111** [pekonchan/scrollNav#7]
我点击跳转到第四个导航但是高亮选中的是第三个

**Comment by pekonchan** [comment]
我更新了一下最新的包，你可以再试下。我这边测试ok


如果还不行，你可能要具体描述下你的使用情况，我才好重现排查问题哦

**Comment by pekonchan** [comment]
> 我点击跳转到第四个导航但是高亮选中的是第三个

之前没引用，不知道你是否收到了

**Comment by yihuoren** [comment]
点击跳转时，同一个tab，点击第一次的时候滚动到对应位置，第二次才会选中状态。需要连续触发同一个tab两次才会得到正确的结果。即选中当前tab且滚动到对应内容区域。

**Comment by yihuoren** [comment]
确实是，最后一个tab需要连续点击两次才会得到正确的结果。即选中且滚动到对应位置

**Comment by yihuoren** [comment]
这个现象在内容区域设置较小时，即每个content高度为300px左右。会复现

**Comment by pekonchan** [comment]
> 这个现象在内容区域设置较小时，即每个content高度为300px左右。会复现

我这边试了下，是可以的。请问你是什么版本的。或者是，你可以截图看看你是怎么使用的，也或者是再具体说说还要什么背景条件，可能影响到了计算滚动。

**Comment by pekonchan** [comment]
因没相关更具体信息反馈。先关闭该issue
